In [1]:
%matplotlib inline
import torch

In [2]:


zz = torch.zeros((3,4,5))
oo = torch.ones(zz.size())
oo = torch.ones_like(zz)
print(oo)

# test scatter
bs = 4
hw = 4
rads = torch.randint(0, hw*hw, (bs,)).long()
rads = torch.unsqueeze(rads, 1)
print(rads)
z = torch.zeros(bs, hw*hw).scatter_(1, rads, 1)
print(z.reshape((bs,hw,hw)))



tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])
tensor([[8],
        [9],
        [3],
        [7]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [1., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 1.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 1.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
